# version: "3.9"
services:
  db:
    image: postgis/postgis:16-3.4
    container_name: logistics_db
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-logi_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-logi_pass}
      POSTGRES_DB: ${POSTGRES_DB:-logistics}
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./infra/postgres/init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-logi_user} -d ${POSTGRES_DB:-logistics}"]
      interval: 5s
      timeout: 5s
      retries: 10

  osrm:
    build: ./infra/osrm
    container_name: osrm_routed
    ports:
      - "5000:5000"
    volumes:
      - ./data/osm:/data
      # - ./infra/osrm/profiles:/opt
    environment:
      - OSM_PBF=/data/region.osm.pbf
      - PROFILE=/opt/car.lua 

volumes:
  db_data:
