# version: "3.9"
services:
  db:
    image: postgis/postgis:16-3.4
    container_name: logistics_db
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-logi_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-logi_pass}
      POSTGRES_DB: ${POSTGRES_DB:-logistics}
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./infra/postgres/init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-logi_user} -d ${POSTGRES_DB:-logistics}"]
      interval: 5s
      timeout: 5s
      retries: 10

  osrm:
    build: ./infra/osrm
    container_name: osrm_routed
    ports:
      - "5000:5000"
    volumes:
      - ./data/osm:/data
      # - ./infra/osrm/profiles:/opt
    environment:
      OSM_PBF: /data/region.osm.pbf
      PROFILE: /opt/car.lua

  backend:
    image: tiangolo/uvicorn-gunicorn-fastapi:python3.11   # Docker Hub image (no GHCR auth needed)
    depends_on:
      - db
    environment:
      PG_DSN: postgres://$${POSTGRES_USER:-logi_user}:$${POSTGRES_PASSWORD:-logi_pass}@db:5432/$${POSTGRES_DB:-logistics}
      DELAY_SERVICE_URL: http://ml-delay:9000
      CORS_ORIGINS: "*"
    volumes:
      - ./backend:/app/backend
    working_dir: /app
    command: ["uvicorn","backend.app.main:app","--host","0.0.0.0","--port","8000","--reload"]
    ports:
      - "8000:8000"

  ml-delay:
    image: python:3.11-slim
    depends_on:
      - db
    environment:
      PG_DSN: postgres://$${POSTGRES_USER:-logi_user}:$${POSTGRES_PASSWORD:-logi_pass}@db:5432/$${POSTGRES_DB:-logistics}
      MODELS_DIR: /srv/models/delay
    volumes:
      - ./ml/delay_service:/srv/app
      - ./models:/srv/models
    working_dir: /srv/app
    command: ["bash","-lc","pip install --no-cache-dir -e . && uvicorn app:app --host 0.0.0.0 --port 9000"]
    ports:
      - "9000:9000"

volumes:
  db_data:
